export const GRID_SIZE = 10;
export const TILE_COUNT = GRID_SIZE * GRID_SIZE;
export const STORAGE_KEY = "farm_idle_save_v1";
export const STARTING_MONEY = 32;
export const GAME_TICK_MS = 250;

export const STAGES = [
  { id: "planted", label: "Planted Seed", durationMs: 20 * 1000 },
  { id: "seedling", label: "Seedling", durationMs: 75 * 1000 },
  { id: "young", label: "Young Plant", durationMs: 5 * 60 * 1000 },
  { id: "mature", label: "Mature Plant", durationMs: 12 * 60 * 1000 },
  { id: "old", label: "Old Plant", durationMs: 30 * 60 * 1000 },
];

export const SEEDS = [
  {
    id: "basic",
    name: "Basic Grain",
    cost: 0,
    matureValue: 4,
    oldValue: 1,
    // Early bailout crop:
    // Seedling -> Mature is ~45s total (12s + 33s), but low payout.
    stageScale: [0.25, 0.16, 0.11, 1.0, 1.1],
    traits: { droughtGuard: 0.3 },
    flavor: "Free emergency crop: very fast to mature, very low payout.",
  },
  {
    id: "turnip",
    name: "Turnip",
    cost: 5,
    matureValue: 86,
    oldValue: 30,
    stageScale: [0.48, 0.52, 0.56, 0.76, 0.84],
    traits: { quick: 0.24 },
    flavor: "Fast cycle, strong early-game money.",
  },
  {
    id: "carrot",
    name: "Crimson Carrot",
    cost: 18,
    matureValue: 280,
    oldValue: 95,
    stageScale: [0.58, 0.66, 0.74, 0.9, 0.98],
    traits: { thrift: 0.12, quick: 0.08 },
    flavor: "Quick, steady cashflow crop.",
  },
  {
    id: "rose",
    name: "Ruby Rose",
    cost: 52,
    matureValue: 620,
    oldValue: 240,
    stageScale: [0.76, 0.84, 0.92, 1.08, 1.16],
    traits: { jackpot: 0.08, quick: 0.05 },
    flavor: "First flower crop. Pretty and profitable.",
  },
  {
    id: "tulip",
    name: "Solar Tulip",
    cost: 95,
    matureValue: 1120,
    oldValue: 450,
    stageScale: [0.88, 0.98, 1.08, 1.24, 1.34],
    traits: { quick: 0.1, thrift: 0.08 },
    flavor: "Fast flower with reliable returns.",
  },
  {
    id: "berry",
    name: "Moonberry",
    cost: 190,
    matureValue: 1250,
    oldValue: 500,
    stageScale: [1.08, 1.16, 1.26, 1.42, 1.52],
    traits: { jackpot: 0.12 },
    flavor: "Balanced growth with big mature harvests.",
  },
  {
    id: "lavender",
    name: "Night Lavender",
    cost: 260,
    matureValue: 1700,
    oldValue: 680,
    stageScale: [1.18, 1.28, 1.38, 1.56, 1.66],
    traits: { droughtGuard: 0.9 },
    flavor: "Fragrant flower with strong mid-game value.",
  },
  {
    id: "corn",
    name: "Sky Corn",
    cost: 340,
    matureValue: 2300,
    oldValue: 920,
    stageScale: [1.3, 1.42, 1.54, 1.74, 1.86],
    traits: { matureBonus: 0.18 },
    flavor: "Strong mid-game earner.",
  },
  {
    id: "sunflower",
    name: "Golden Sunflower",
    cost: 500,
    matureValue: 3600,
    oldValue: 1450,
    stageScale: [1.44, 1.58, 1.72, 1.94, 2.08],
    traits: { regrow: 0.12 },
    flavor: "Tall flower with bright mature payouts.",
  },
  {
    id: "pumpkin",
    name: "Titan Pumpkin",
    cost: 720,
    matureValue: 6200,
    oldValue: 2500,
    stageScale: [1.6, 1.76, 1.9, 2.14, 2.28],
    traits: { matureBonus: 0.35, droughtGuard: 0.5 },
    flavor: "Slow but very profitable if managed well.",
  },
  {
    id: "lotus",
    name: "Gold Lotus",
    cost: 1400,
    matureValue: 14200,
    oldValue: 6000,
    stageScale: [1.8, 1.98, 2.14, 2.38, 2.54],
    traits: { jackpot: 0.18 },
    flavor: "Expensive premium seed with huge payoff.",
  },
  {
    id: "cacao",
    name: "Night Cacao",
    cost: 2700,
    matureValue: 32000,
    oldValue: 13500,
    stageScale: [2.02, 2.22, 2.4, 2.66, 2.82],
    traits: { jackpot: 0.22, matureBonus: 0.3 },
    flavor: "Late-game crop for big bankroll growth.",
  },
];

// Per-seed pricing curves let us bias different crops to shine at different
// marketing bands, while still layering demand inflation/decay on top.
export const SEED_PRICE_CURVES = {
  basic: {
    preferredMarketingMin: 0,
    preferredMarketingMax: 0,
    inBandMultiplier: 1,
    inBandYieldBonus: 0,
    earlySlope: 0,
    lateSlope: 0.12,
    minMultiplier: 1,
    maxMultiplier: 3.2,
    demandGrowthBase: 1.2,
    demandHalfLifeMs: 2.5 * 60 * 1000,
    demandMaxMultiplier: 3.5,
  },
  turnip: {
    preferredMarketingMin: 0,
    preferredMarketingMax: 3,
    inBandMultiplier: 0.48,
    inBandYieldBonus: 0.22,
    earlySlope: 0.02,
    lateSlope: 0.09,
    minMultiplier: 0.5,
    maxMultiplier: 3.4,
    demandGrowthBase: 1.02,
    demandHalfLifeMs: 2.5 * 60 * 1000,
    demandMaxMultiplier: 5,
  },
  carrot: {
    preferredMarketingMin: 1,
    preferredMarketingMax: 4,
    inBandMultiplier: 0.54,
    inBandYieldBonus: 0.24,
    earlySlope: 0.03,
    lateSlope: 0.085,
    minMultiplier: 0.54,
    maxMultiplier: 3.4,
    demandGrowthBase: 1.025,
    demandHalfLifeMs: 2.8 * 60 * 1000,
    demandMaxMultiplier: 5.5,
  },
  rose: {
    preferredMarketingMin: 2,
    preferredMarketingMax: 5,
    inBandMultiplier: 0.62,
    inBandYieldBonus: 0.22,
    earlySlope: 0.04,
    lateSlope: 0.08,
    minMultiplier: 0.58,
    maxMultiplier: 3.5,
    demandGrowthBase: 1.03,
    demandHalfLifeMs: 3 * 60 * 1000,
    demandMaxMultiplier: 5.8,
  },
  tulip: {
    preferredMarketingMin: 3,
    preferredMarketingMax: 6,
    inBandMultiplier: 0.68,
    inBandYieldBonus: 0.2,
    earlySlope: 0.045,
    lateSlope: 0.08,
    minMultiplier: 0.62,
    maxMultiplier: 3.6,
    demandGrowthBase: 1.035,
    demandHalfLifeMs: 3.2 * 60 * 1000,
    demandMaxMultiplier: 6,
  },
  berry: {
    preferredMarketingMin: 4,
    preferredMarketingMax: 7,
    inBandMultiplier: 0.79,
    inBandYieldBonus: 0.1,
    earlySlope: 0.09,
    lateSlope: 0.08,
    minMultiplier: 0.83,
    maxMultiplier: 3.8,
    demandGrowthBase: 1.09,
    demandHalfLifeMs: 4.2 * 60 * 1000,
    demandMaxMultiplier: 6.2,
  },
  lavender: {
    preferredMarketingMin: 5,
    preferredMarketingMax: 7,
    inBandMultiplier: 0.88,
    inBandYieldBonus: 0.08,
    earlySlope: 0.1,
    lateSlope: 0.08,
    minMultiplier: 0.82,
    maxMultiplier: 4,
    demandGrowthBase: 1.085,
    demandHalfLifeMs: 4.4 * 60 * 1000,
    demandMaxMultiplier: 6.5,
  },
  corn: {
    preferredMarketingMin: 6,
    preferredMarketingMax: 8,
    inBandMultiplier: 0.87,
    inBandYieldBonus: 0.08,
    earlySlope: 0.11,
    lateSlope: 0.08,
    minMultiplier: 0.82,
    maxMultiplier: 4.2,
    demandGrowthBase: 1.08,
    demandHalfLifeMs: 4.8 * 60 * 1000,
    demandMaxMultiplier: 7,
  },
  sunflower: {
    preferredMarketingMin: 7,
    preferredMarketingMax: 9,
    inBandMultiplier: 0.86,
    inBandYieldBonus: 0.08,
    earlySlope: 0.12,
    lateSlope: 0.08,
    minMultiplier: 0.8,
    maxMultiplier: 4.4,
    demandGrowthBase: 1.075,
    demandHalfLifeMs: 5 * 60 * 1000,
    demandMaxMultiplier: 7.2,
  },
  pumpkin: {
    preferredMarketingMin: 8,
    preferredMarketingMax: 11,
    inBandMultiplier: 0.85,
    inBandYieldBonus: 0.1,
    earlySlope: 0.13,
    lateSlope: 0.07,
    minMultiplier: 0.78,
    maxMultiplier: 4.8,
    demandGrowthBase: 1.07,
    demandHalfLifeMs: 5.5 * 60 * 1000,
    demandMaxMultiplier: 7.8,
  },
  lotus: {
    preferredMarketingMin: 10,
    preferredMarketingMax: 13,
    inBandMultiplier: 0.84,
    inBandYieldBonus: 0.12,
    earlySlope: 0.14,
    lateSlope: 0.07,
    minMultiplier: 0.76,
    maxMultiplier: 5.2,
    demandGrowthBase: 1.06,
    demandHalfLifeMs: 6 * 60 * 1000,
    demandMaxMultiplier: 8.5,
  },
  cacao: {
    preferredMarketingMin: 12,
    preferredMarketingMax: 16,
    inBandMultiplier: 0.82,
    inBandYieldBonus: 0.14,
    earlySlope: 0.15,
    lateSlope: 0.06,
    minMultiplier: 0.74,
    maxMultiplier: 5.8,
    demandGrowthBase: 1.05,
    demandHalfLifeMs: 7 * 60 * 1000,
    demandMaxMultiplier: 10,
  },
};

export const TOOLS = [
  { id: "plow", label: "Plow" },
  { id: "plant", label: "Seeds" },
  { id: "water", label: "Water" },
  { id: "harvest", label: "Harvest" },
  { id: "marketing", label: "Marketing" },
  { id: "expandFarm", label: "Farm" },
  { id: "animals", label: "Animals" },
  { id: "research", label: "Research" },
  { id: "save", label: "Save" },
];

export const ACTION_TOOLS = ["plow", "plant", "water", "harvest"];
export const BRUSHES = [
  { id: "1x1", width: 1, height: 1, cost: 0 },
  { id: "1x2", width: 1, height: 2, cost: 350 },
  { id: "2x1", width: 2, height: 1, cost: 350 },
  { id: "2x2", width: 2, height: 2, cost: 1100 },
  { id: "3x3", width: 3, height: 3, cost: 3200 },
  { id: "4x4", width: 4, height: 4, cost: 12000 },
  { id: "5x5", width: 5, height: 5, cost: 30000 },
];

export const AUTOMATION_COSTS = {
  autoPlow: 1100,
  autoWater: 1700,
  autoPlant: 2600,
  autoHarvest: 4200,
  autoEverything: 17500,
};

export const SEED_UNLOCK_ORDER = SEEDS.map((s) => s.id);
export const SOIL_DECAY_MS = 30 * 60 * 1000;
export const SEED_DEMAND_GROWTH_BASE = 1.04;
export const SEED_DEMAND_HALF_LIFE_MS = 2.75 * 60 * 1000;
export const SEED_DEMAND_PER_PLANT = 0.45;
export const SEED_DEMAND_MAX_MULTIPLIER = 6.5;
export const OVERDUE_WATER_GRACE_FACTOR = 4.0;
export const OVERDUE_WATER_GRACE_MIN_MS = 90 * 1000;
export const LATE_WATER_DELAY_FRACTION = 0.1;
export const OLD_UNHARVESTED_GRACE_FACTOR = 24;
export const OLD_UNHARVESTED_GRACE_MIN_MS = 6 * 60 * 60 * 1000;
export const PRESTIGE_BASE_MONEY = 760;
export const PRESTIGE_COST_GROWTH = 1.3;
export const MARKETING_UNLOCK_MONEY = 760;
export const RESEARCH_UNLOCK_MARKETING = 1;
export const PRESTIGE_START_MONEY_PER_LEVEL = 30;
export const PRESTIGE_GROWTH_SPEED_PER_LEVEL = 0.06;
export const PRESTIGE_MAX_GROWTH_SPEED = 0.6;
export const MAX_ANIMALS_PER_TILE = 3;
export const ANIMAL_ANIM_CYCLE = [0, 1, 2, 1];
export const ANIMAL_ANIM_INTERVAL_MS = 520;
export const ANIMAL_PRESTIGE_OFFSET = 1;
export const FARM_EXPANSIONS = [
  { size: 3, reqPrestige: 0, unlockShards: 0 },
  { size: 4, reqPrestige: 1, unlockShards: 6 },
  { size: 5, reqPrestige: 2, unlockShards: 20 },
  { size: 7, reqPrestige: 3, unlockShards: 55 },
  { size: 8, reqPrestige: 4, unlockShards: 120 },
  { size: 9, reqPrestige: 5, unlockShards: 300 },
  { size: 10, reqPrestige: 6, unlockShards: 700 },
];

export const ANIMALS = [
  {
    id: "chicken",
    name: "Chicken",
    unlockShards: 1,
    traits: { quick: 0.14 },
    desc: "Speeds growth on this tile.",
  },
  {
    id: "cow",
    name: "Cow",
    unlockShards: 2,
    traits: { matureBonus: 0.45 },
    desc: "Boosts mature harvest value.",
  },
  {
    id: "bee",
    name: "Bee",
    unlockShards: 4,
    traits: { jackpot: 0.25 },
    desc: "Raises jackpot chance.",
  },
  {
    id: "pig",
    name: "Pig",
    unlockShards: 6,
    traits: { droughtGuard: 1.3, matureBonus: 0.22 },
    desc: "Protects drought-prone crops and boosts value.",
  },
  {
    id: "rabbit",
    name: "Rabbit",
    unlockShards: 9,
    traits: { quick: 0.28, regrow: 0.14 },
    desc: "Fast hopper that accelerates growth and regrow chance.",
  },
  {
    id: "goat",
    name: "Goat",
    unlockShards: 13,
    traits: { thrift: 0.3, matureBonus: 0.26 },
    desc: "Cuts seed spend and improves mature sale value.",
  },
  {
    id: "duck",
    name: "Duck",
    unlockShards: 18,
    traits: { droughtGuard: 1.8, quick: 0.12 },
    desc: "Water-wise helper with a light speed boost.",
  },
  {
    id: "fox",
    name: "Fox",
    unlockShards: 24,
    traits: { jackpot: 0.4 },
    desc: "High-risk luck specialist for bigger jackpot hits.",
  },
  {
    id: "alpaca",
    name: "Alpaca",
    unlockShards: 34,
    traits: { matureBonus: 0.75, thrift: 0.18 },
    desc: "Premium value booster for late-game harvests.",
  },
  {
    id: "firefly",
    name: "Firefly",
    unlockShards: 46,
    traits: { quick: 0.22, jackpot: 0.28, regrow: 0.28 },
    desc: "Rare glow buff with speed, luck, and regrow synergy.",
  },
];

export const MARKET_ROTATION_MS = 8 * 60 * 1000;
export const MARKET_SEASONS = [
  {
    id: "root_rush",
    label: "Root Rush",
    categories: ["root"],
    baseBonus: 0.36,
    synergyAnimal: "rabbit",
    synergyBonus: 0.14,
  },
  {
    id: "flower_festival",
    label: "Flower Festival",
    categories: ["flower"],
    baseBonus: 0.39,
    synergyAnimal: "bee",
    synergyBonus: 0.16,
  },
  {
    id: "grain_boom",
    label: "Grain Boom",
    categories: ["grain"],
    baseBonus: 0.32,
    synergyAnimal: "chicken",
    synergyBonus: 0.14,
  },
  {
    id: "orchard_bounty",
    label: "Orchard Bounty",
    categories: ["fruit"],
    baseBonus: 0.38,
    synergyAnimal: "fox",
    synergyBonus: 0.16,
  },
  {
    id: "royal_market",
    label: "Royal Market",
    categories: ["gourd", "luxury"],
    baseBonus: 0.45,
    synergyAnimal: "alpaca",
    synergyBonus: 0.18,
  },
];

export const SHARD_UPGRADES = [
  {
    id: "seed_lab",
    label: "Seed Lab",
    cap: 12,
    baseCost: 5,
    growth: 1.38,
    minMarketing: 1,
    desc: "Starter lab: permanent seed thrift for all crops.",
  },
  {
    id: "harvest_lab",
    label: "Harvest Lab",
    cap: 12,
    baseCost: 7,
    growth: 1.42,
    minMarketing: 1,
    desc: "Starter lab: permanent mature harvest value boost.",
  },
  {
    id: "luck_lab",
    label: "Luck Lab",
    cap: 10,
    baseCost: 14,
    growth: 1.56,
    minMarketing: 3,
    desc: "Advanced lab: permanent jackpot chance boost.",
  },
  {
    id: "regrow_lab",
    label: "Regrow Lab",
    cap: 10,
    baseCost: 20,
    growth: 1.6,
    minMarketing: 3,
    desc: "Advanced lab: permanent regrow chance boost.",
  },
  {
    id: "market_lab",
    label: "Market Lab",
    cap: 8,
    baseCost: 26,
    growth: 1.66,
    minMarketing: 3,
    desc: "Advanced lab: increases market-season bonus strength.",
  },
];

export const PRESTIGE_MILESTONES = [
  {
    id: "p1",
    reqPrestige: 1,
    rewardShards: 8,
    title: "Tiny Tractor Energy",
    desc: "Early platinum boost for your first upgrades.",
  },
  {
    id: "p2",
    reqPrestige: 2,
    rewardShards: 14,
    title: "Dirt Doesn't Sleep",
    desc: "Smooths early expansion and automation picks.",
  },
  {
    id: "p3",
    reqPrestige: 3,
    rewardShards: 20,
    title: "Sprout About It",
    desc: "Keeps momentum through the early midgame.",
  },
  {
    id: "p4",
    reqPrestige: 4,
    rewardShards: 28,
    title: "Hoe-ver Achiever",
    desc: "Adds meaningful pre-M5 progression pacing.",
  },
  {
    id: "p5",
    reqPrestige: 5,
    rewardShards: 40,
    title: "Compost and Circumstance",
    desc: "Funds early research and farm progression.",
  },
  {
    id: "p6",
    reqPrestige: 6,
    rewardShards: 36,
    title: "Mud, Sweat, and Tiers",
    desc: "Adds a stronger midgame platinum burst.",
  },
  {
    id: "p7",
    reqPrestige: 7,
    rewardShards: 50,
    title: "Cash Crop Chaos",
    desc: "Supports broader seed and automation choices.",
  },
  {
    id: "p8",
    reqPrestige: 8,
    rewardShards: 70,
    title: "Field Marshal",
    desc: "Bridges early progression into sustained loops.",
  },
  {
    id: "p9",
    reqPrestige: 9,
    rewardShards: 95,
    title: "Barn of Legends",
    desc: "Keeps momentum high ahead of milestone tiers.",
  },
  {
    id: "p10",
    reqPrestige: 10,
    rewardShards: 350,
    title: "Plateau? Never Heard of Her",
    desc: "Large platinum grant for established farms.",
  },
  {
    id: "p12",
    reqPrestige: 12,
    rewardShards: 700,
    title: "Agronomicon Unlocked",
    desc: "Midgame platinum injection for build choices.",
  },
  {
    id: "p13",
    reqPrestige: 13,
    rewardShards: 840,
    title: "Yield Boss",
    desc: "Extra midgame tempo reward.",
  },
  {
    id: "p14",
    reqPrestige: 14,
    rewardShards: 980,
    title: "Profit Prophet",
    desc: "Extra midgame choice point before higher tiers.",
  },
  {
    id: "p15",
    reqPrestige: 15,
    rewardShards: 1600,
    title: "The Harvest Council",
    desc: "Push into higher farm and animal tiers.",
  },
  {
    id: "p18",
    reqPrestige: 18,
    rewardShards: 3600,
    title: "Empire of Soil",
    desc: "Late-game momentum spike.",
  },
  {
    id: "p22",
    reqPrestige: 22,
    rewardShards: 8500,
    title: "Platinum Plow Supreme",
    desc: "Pre-reset prep package.",
  },
];

